import Header from 'components/Header';
import Head from "next/head";
import styles from './Layout.module.css';

export default function Layout({ title, children }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>{children}</main>
    </div>
  );
}
